// ============================================================
// KELAAS — Helper DB untuk Vercel + Supabase (Postgres).
//
// API TETAP SAMA dengan versi D1 (all/one/run/insertId/args/num/s)
// supaya seluruh routes (src/api/*) tidak perlu diubah:
//   • Query pakai placeholder `?` → dikonversi otomatis ke $1,$2,...
//   • INSERT ... RETURNING id → ganti last_insert_rowid()
//   • INSERT OR IGNORE       → ON CONFLICT DO NOTHING
//   • datetime('now','+7 hours') → NOW() AT TIME ZONE 'Asia/Jakarta'
//
// Koneksi: Supabase pooled connection (port 6543, Transaction
// mode) via pg Pool. DATABASE_URL di-set di Vercel Environment
// Variables. Kolom id INTEGER AUTOINCREMENT di schema diubah
// jadi BIGINT GENERATED BY DEFAULT AS IDENTITY — jadi INSERT
// eksplisit dengan id tetap bisa (import data), dan tanpa id
// auto-generate.
// ============================================================
import pg from 'pg';

// Node runtime di Vercel punya env NODE_TLS kekhawatiran khusus:
// Supabase pooler pakai sertifikat; default verify-full aman.
const { Pool } = pg;

let pool: pg.Pool | null = null;

export function getPool(): pg.Pool {
  if (pool) return pool;
  const cs = process.env.DATABASE_URL || process.env.POSTGRES_URL || '';
  if (!cs) throw new Error('DATABASE_URL tidak diset — isi di Vercel Env / .env.local');
  const needsSsl = /sslmode=require|supabase\.(co|com)|pooler\.supabase/.test(cs);
  pool = new Pool({
    connectionString: cs,
    ssl: needsSsl ? { rejectUnauthorized: false } : undefined,
    max: Number(process.env.PG_POOL_MAX ?? 5),
    idleTimeoutMillis: 30_000,
    connectionTimeoutMillis: 10_000,
  });
  // Jangan crash proses karena koneksi idle error.
  pool.on('error', (e) => console.error('[pg-pool-idle-error]', e.message));
  return pool;
}

export interface CtxDB {
  DB: any; // disimpan hanya untuk kompatibilitas tipe lama (tidak dipakai)
}

export function num(v: unknown): number {
  if (v === null || v === undefined) return 0;
  const n = Number(v);
  return Number.isNaN(n) ? 0 : n;
}

export function s(v: unknown): string {
  if (v === null || v === undefined) return '';
  return String(v);
}

// Siapkan argumen; Postgres strict — null bukan undefined.
export function args(values: unknown[]): (string | number | boolean | null)[] {
  return values.map((v) => {
    if (v === undefined || v === null) return null;
    if (typeof v === 'number' || typeof v === 'string' || typeof v === 'boolean') return v;
    return String(v);
  });
}

// ------------------------------------------------------------
// Konversi SQL SQLite/D1 → Postgres.
//   • `?`  → $1, $2, ...
//   • INSERT OR IGNORE INTO → INSERT INTO ... ON CONFLICT DO NOTHING
//     (tanpa klausa konflik spesifik → aman untuk semua tabel;
//      menangkap unique constraint apa pun)
//   • datetime('now','+7 hours') → to_char(NOW() AT TIME ZONE 'Asia/Jakarta','YYYY-MM-DD HH24:MI:SS')
//   • datetime('now') → to_char(NOW(),'YYYY-MM-DD HH24:MI:SS')
//   • substr(x,y) → substr(x,y) sama di Postgres — tidak diubah
// ------------------------------------------------------------
function toPg(sql: string, values: unknown[]): { sql: string; values: (string | number | boolean | null)[] } {
  let idx = 0;
  let out = '';
  for (let i = 0; i < sql.length; i++) {
    const ch = sql[i];
    if (ch === '?' && sql[i + 1] !== '?') {
      idx++;
      out += '$' + idx;
    } else {
      out += ch;
    }
  }
  let sql2 = out;
  // SQLite AUTOINCREMENT (dipakai endpoint setup / ensureCbtColumns versi lama)
  sql2 = sql2.replace(
    /\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi,
    'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
  );
  // INSERT OR IGNORE
  sql2 = sql2.replace(/\bINSERT\s+OR\s+IGNORE\s+INTO\b/gi, 'INSERT INTO');
  if (/\bINSERT\s+INTO\b/i.test(sql2) && /\bINSERT\s+OR\s+IGNORE\b/i.test(sql)) {
    sql2 = sql2.trimEnd().replace(/;$/, '') + ' ON CONFLICT DO NOTHING';
  }
  // datetime('now','+7 hours') dan datetime('now') — dua-duanya di-quote
  // dalam query asli; ganti sebagai ekspresi literal.
  sql2 = sql2.replace(
    /datetime\(\s*'now'\s*,\s*'\+7 hours'\s*\)/gi,
    `to_char(NOW() AT TIME ZONE 'Asia/Jakarta', 'YYYY-MM-DD HH24:MI:SS')`,
  );
  sql2 = sql2.replace(/datetime\(\s*'now'\s*\)/gi, `to_char(NOW() AT TIME ZONE 'Asia/Jakarta', 'YYYY-MM-DD HH24:MI:SS')`);
  return { sql: sql2, values: args(values) };
}

// Ambil semua baris → array objek (normalisasi snake_case→snake_case, sama seperti D1).
export async function all<T = Record<string, unknown>>(
  db: any,
  sql: string,
  values: unknown[] = [],
): Promise<T[]> {
  const q = toPg(sql, values);
  try {
    const res = await getPool().query(q.sql, q.values);
    return res.rows as T[];
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    console.error('[db.all]', msg, '| SQL:', q.sql.slice(0, 200));
    throw e;
  }
}

// Ambil satu baris atau null.
export async function one<T = Record<string, unknown>>(
  db: any,
  sql: string,
  values: unknown[] = [],
): Promise<T | null> {
  const rows = await all<T>(db, sql, values);
  return rows[0] ?? null;
}

// Eksekusi tanpa hasil (INSERT/UPDATE/DELETE/DDL).
export async function run(db: any, sql: string, values: unknown[] = []): Promise<void> {
  const q = toPg(sql, values);
  try {
    await getPool().query(q.sql, q.values);
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    console.error('[db.run]', msg, '| SQL:', q.sql.slice(0, 200));
    throw e;
  }
}

// INSERT lalu kembalikan id baru. Postgres butuh RETURNING id;
// ditambahkan otomatis jika query INSERT tanpa RETURNING.
export async function insertId(db: any, sql: string, values: unknown[] = []): Promise<number> {
  let q = toPg(sql, values);
  if (/\bINSERT\b/i.test(q.sql) && !/\bRETURNING\b/i.test(q.sql)) {
    q = { ...q, sql: q.sql.trimEnd().replace(/;$/, '') + ' RETURNING id' };
  }
  try {
    const res = await getPool().query(q.sql, q.values);
    const row = res.rows[0] as Record<string, unknown> | undefined;
    if (!row) return 0;
    const v = row.id ?? row.ID ?? Object.values(row)[0];
    return num(v);
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    console.error('[db.insertId]', msg, '| SQL:', q.sql.slice(0, 200));
    throw e;
  }
}

// Banyak statement DDL sekaligus (CREATE TABLE IF NOT EXISTS ...).
// Postgres: jalankan satu per satu, kumpulkan error seperti versi D1.
export async function runBatch(db: any, statements: string[]): Promise<{ ok: number; errs: string[] }> {
  let ok = 0;
  const errs: string[] = [];
  for (const sql of statements) {
    try {
      await run(db, sql);
      ok++;
    } catch (e: unknown) {
      errs.push(String(e instanceof Error ? e.message : e));
    }
  }
  return { ok, errs };
}

// ------------------------------------------------------------
// Self-heal migrasi CBT anti-mencontek (migrasi 0010).
// Bila DB produksi belum di-migrasi, kolom `locked`/`violations`/
// `locked_at`/`approved_at` + tabel `cbt_pelanggaran` ditambahkan
// otomatis (idempoten). Dipanggil dari handler CBT agar query
// `locked`/`violations` tidak pernah error "column does not exist".
// ------------------------------------------------------------
export async function ensureCbtColumns(db: any): Promise<void> {
  // Tabel pelanggaran (CREATE IF NOT EXISTS — aman dijalankan berulang).
  try {
    await run(
      db,
      `CREATE TABLE IF NOT EXISTS cbt_pelanggaran (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          sesi_id BIGINT,
          ujian_id BIGINT,
          nis TEXT,
          nama TEXT,
          jenis TEXT DEFAULT 'tab',
          detail TEXT,
          waktu TEXT,
          status TEXT DEFAULT 'pending'
        )`,
    );
  } catch {
    // abaikan — query berikut yang menangani bila tabel rusak
  }

  // Cek kolom yang sudah ada di cbt_sesi (Postgres information_schema).
  const cols = new Set<string>();
  try {
    const rows = await all<{ column_name: string }>(
      db,
      `SELECT column_name FROM information_schema.columns WHERE table_name='cbt_sesi'`,
    );
    for (const r of rows) cols.add(String(r.column_name ?? ''));
  } catch {
    return; // tabel cbt_sesi belum ada — biarkan handler yang menangani
  }

  const need: [string, string][] = [
    ['violations', 'INTEGER DEFAULT 0'],
    ['locked', 'INTEGER DEFAULT 0'],
    ['locked_at', 'TEXT'],
    ['approved_at', 'TEXT'],
  ];
  for (const [col, typ] of need) {
    if (cols.has(col)) continue;
    try {
      await run(db, `ALTER TABLE cbt_sesi ADD COLUMN ${col} ${typ}`);
    } catch {
      // race / kolom baru saja dibuat — abaikan
    }
  }
}
