-- Cloudflare D1 / SQLite schema converted from MySQL
CREATE TABLE agenda_mengajar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nip TEXT ,
  tanggal TEXT ,
  kelas TEXT ,
  mapel TEXT ,
  target TEXT ,
  materi TEXT ,
  deadline TEXT ,
  status TEXT 
);
CREATE TABLE bahan_praktik (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode TEXT ,
  nama_bahan TEXT ,
  satuan TEXT ,
  stok REAL ,
  stok_min REAL ,
  kategori TEXT 
);
CREATE TABLE bank_soal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nip TEXT NOT NULL,
  mapel TEXT ,
  kelas TEXT DEFAULT '',
  jenis INTEGER DEFAULT 1,
  soal TEXT ,
  opsi TEXT ,
  kunci TEXT ,
  pembahasan TEXT ,
  bobot INTEGER DEFAULT 1,
  tanggal TEXT 
);
CREATE TABLE catatan_perilaku (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nip TEXT ,
  kelas TEXT ,
  nis TEXT ,
  jenis TEXT ,
  keterangan TEXT ,
  poin INTEGER ,
  tanggal TEXT 
);
CREATE TABLE catatan_sikap (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal TEXT ,
  kelas TEXT ,
  nis TEXT ,
  jenis TEXT ,
  keterangan TEXT ,
  poin INTEGER ,
  pencatat TEXT 
);
CREATE TABLE cbt_exam (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nip TEXT ,
  kelas TEXT ,
  mapel TEXT ,
  judul TEXT ,
  durasi INTEGER ,
  token TEXT ,
  acak_soal INTEGER DEFAULT 0,
  status TEXT DEFAULT 'Aktif',
  tanggal TEXT 
);
CREATE TABLE cbt_hasil (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_id INTEGER ,
  nis TEXT ,
  nama TEXT ,
  mulai TEXT ,
  selesai TEXT ,
  nilai_pg REAL ,
  nilai_essay REAL ,
  total REAL ,
  status TEXT DEFAULT 'Berlangsung',
  CONSTRAINT uniq_exam_nis UNIQUE (exam_id, nis)
);
CREATE TABLE cbt_jawaban (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sesi_id INTEGER ,
  soal_id INTEGER ,
  jawaban TEXT ,
  benar INTEGER ,
  feedback TEXT ,
  sumber TEXT NOT NULL DEFAULT 'manual',
  CONSTRAINT uniq_sesi_soal UNIQUE (sesi_id, soal_id)
);
CREATE TABLE cbt_sesi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ujian_id INTEGER ,
  nis TEXT ,
  nama TEXT ,
  mulai TEXT ,
  deadline TEXT ,
  selesai INTEGER DEFAULT 0,
  skor REAL ,
  total_benar INTEGER DEFAULT 0,
  total_soal INTEGER DEFAULT 0,
  uraian_menunggu INTEGER DEFAULT 0
);
CREATE TABLE cbt_soal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ujian_id INTEGER ,
  no_urut INTEGER ,
  jenis INTEGER ,
  soal TEXT ,
  opsi TEXT ,
  kunci TEXT ,
  pembahasan TEXT ,
  bobot INTEGER DEFAULT 1
);
CREATE TABLE cbt_ujian (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nip TEXT ,
  judul TEXT ,
  kelas TEXT ,
  mapel TEXT ,
  durasi_menit INTEGER DEFAULT 60,
  token TEXT ,
  aktif INTEGER DEFAULT 1,
  ai_aktif INTEGER NOT NULL DEFAULT 0,
  tanggal TEXT 
);
CREATE TABLE dokumen (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nip TEXT ,
  jenis TEXT ,
  judul TEXT ,
  url TEXT ,
  keterangan TEXT 
);
CREATE TABLE guru (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nip TEXT NOT NULL,
  nama_guru TEXT ,
  mapel TEXT ,
  kelas_diampu TEXT 
);
CREATE TABLE guru_profil (
  nip TEXT NOT NULL PRIMARY KEY,
  nama TEXT ,
  nip2 TEXT ,
  mapel TEXT ,
  beban INTEGER DEFAULT 0,
  foto TEXT ,
  ttd TEXT 
);
CREATE TABLE inventaris (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kelas TEXT ,
  nama_barang TEXT ,
  jumlah INTEGER ,
  kondisi TEXT ,
  keterangan TEXT ,
  tanggal TEXT 
);
CREATE TABLE jadwal_pelajaran (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kelas TEXT ,
  hari TEXT ,
  jam_ke INTEGER ,
  mata_pelajaran TEXT ,
  nip TEXT 
);
CREATE TABLE jadwal_piket (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kelas TEXT ,
  hari TEXT ,
  nis TEXT ,
  nama_siswa TEXT 
);
CREATE TABLE jurnal_bimbingan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal TEXT ,
  kelas TEXT ,
  kategori TEXT ,
  isi TEXT ,
  tindak_lanjut TEXT 
);
CREATE TABLE jurnal_mengajar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal TEXT ,
  kelas TEXT ,
  nip TEXT ,
  mapel TEXT ,
  jam_ke INTEGER ,
  materi TEXT ,
  kegiatan TEXT ,
  tujuan TEXT ,
  model TEXT ,
  metode TEXT ,
  media TEXT ,
  asesmen TEXT ,
  refleksi TEXT ,
  hambatan TEXT ,
  solusi TEXT ,
  status TEXT DEFAULT 'Selesai'
);
CREATE TABLE kalender_akademik (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal TEXT ,
  jenis TEXT ,
  judul TEXT ,
  keterangan TEXT 
);
CREATE TABLE kaskelas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal TEXT ,
  kelas TEXT ,
  jenis TEXT ,
  jumlah REAL ,
  keterangan TEXT 
);
CREATE TABLE katalog_alat (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode TEXT ,
  nama_barang TEXT ,
  spesifikasi TEXT ,
  jumlah INTEGER ,
  kondisi TEXT ,
  lokasi TEXT 
);
CREATE TABLE kehadiran (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal TEXT ,
  nis TEXT ,
  kelas TEXT ,
  status TEXT ,
  keterangan TEXT ,
  terlambat INTEGER DEFAULT 0
);
CREATE TABLE kkm (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nip TEXT ,
  mapel TEXT ,
  kelas TEXT ,
  nilai_kkm REAL DEFAULT 75.00
);
CREATE TABLE kunjungan_rumah (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal TEXT ,
  nis TEXT ,
  kelas TEXT ,
  nama_siswa TEXT ,
  alamat TEXT ,
  hasil TEXT ,
  tindak_lanjut TEXT ,
  petugas TEXT 
);
CREATE TABLE laporan_kerusakan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal TEXT ,
  kode_barang TEXT ,
  nama_barang TEXT ,
  kerusakan TEXT ,
  pelapor TEXT ,
  status TEXT ,
  jadwal_maintenance TEXT 
);
CREATE TABLE log_aktivitas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  waktu TEXT ,
  username TEXT ,
  role TEXT ,
  aksi TEXT ,
  detail TEXT 
);
CREATE TABLE materi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nip TEXT ,
  kelas TEXT ,
  mapel TEXT ,
  bab TEXT ,
  judul TEXT ,
  jenis TEXT ,
  url TEXT ,
  ket TEXT 
);
CREATE TABLE modul_ajar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nip TEXT ,
  jenis TEXT ,
  judul TEXT ,
  url TEXT ,
  ket TEXT 
);
CREATE TABLE nilai (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nis TEXT ,
  kelas TEXT ,
  nip TEXT ,
  mapel TEXT ,
  jenis TEXT ,
  nilai REAL ,
  tanggal TEXT 
);
CREATE TABLE peminjaman (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pinjam TEXT ,
  kode_barang TEXT ,
  nama_barang TEXT ,
  peminjam TEXT ,
  jenis_peminjam TEXT ,
  tgl_pinjam TEXT ,
  batas_waktu TEXT ,
  status TEXT ,
  tgl_kembali TEXT 
);
CREATE TABLE pengumpulan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tugas_id INTEGER ,
  nis TEXT ,
  file_url TEXT ,
  teks TEXT ,
  nilai REAL ,
  feedback TEXT ,
  tgl_kumpul TEXT 
);
CREATE TABLE pengumuman (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kelas TEXT ,
  judul TEXT ,
  isi TEXT ,
  tanggal TEXT ,
  penulis TEXT 
);
CREATE TABLE portofolio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nis TEXT ,
  nip TEXT ,
  jenis TEXT ,
  judul TEXT ,
  url TEXT ,
  ket TEXT ,
  tanggal TEXT 
);
CREATE TABLE presensi_guru (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nip TEXT ,
  tanggal TEXT ,
  jam_masuk TEXT ,
  jam_selesai TEXT ,
  kelas TEXT ,
  lokasi TEXT ,
  foto TEXT ,
  status TEXT 
);
CREATE TABLE presensi_mapel (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal TEXT ,
  kelas TEXT ,
  nis TEXT ,
  nip TEXT ,
  mapel TEXT ,
  status TEXT ,
  jam_ke INTEGER ,
  created_at TEXT ,
  updated_at TEXT 
);
CREATE TABLE rubrik (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nip TEXT ,
  nama TEXT ,
  komponen TEXT 
);
CREATE TABLE settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key TEXT NOT NULL,
  setting_value TEXT ,
  CONSTRAINT setting_key UNIQUE (setting_key)
);
CREATE TABLE siswa (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nis TEXT NOT NULL,
  nama_siswa TEXT NOT NULL,
  kelas TEXT ,
  jk TEXT ,
  ttl TEXT DEFAULT '',
  alamat TEXT DEFAULT '',
  no_wa TEXT DEFAULT '',
  ekstra TEXT DEFAULT '',
  nama_ayah TEXT DEFAULT '',
  nama_ibu TEXT DEFAULT '',
  kerja_ayah TEXT DEFAULT '',
  kerja_ibu TEXT DEFAULT '',
  penghasilan_ortu TEXT DEFAULT ''
);
CREATE TABLE siswa_meta (
  nis TEXT NOT NULL PRIMARY KEY,
  kontak_darurat TEXT ,
  catatan_medis TEXT 
);
CREATE TABLE struktur_kelas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kelas TEXT ,
  jabatan TEXT ,
  nis TEXT ,
  nama_siswa TEXT 
);
CREATE TABLE tatatertib (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal TEXT ,
  nis TEXT ,
  pelanggaran TEXT ,
  poin INTEGER ,
  kelas TEXT 
);
CREATE TABLE tugas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nip TEXT ,
  kelas TEXT ,
  mapel TEXT ,
  judul TEXT ,
  deadline TEXT ,
  instruksi TEXT ,
  lampiran TEXT ,
  rubrik_id INTEGER 
);
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  kelas TEXT ,
  nama_lengkap TEXT ,
  nip TEXT ,
  CONSTRAINT username UNIQUE (username)
);
CREATE INDEX IF NOT EXISTS idx_nip ON agenda_mengajar (nip);
CREATE INDEX IF NOT EXISTS idx_nip ON bank_soal (nip);
CREATE INDEX IF NOT EXISTS idx_nip_mapel ON bank_soal (nip, mapel);
CREATE INDEX IF NOT EXISTS idx_nip ON catatan_perilaku (nip);
CREATE INDEX IF NOT EXISTS idx_kelas ON catatan_sikap (kelas);
CREATE INDEX IF NOT EXISTS idx_nis ON catatan_sikap (nis);
CREATE INDEX IF NOT EXISTS idx_nip ON cbt_exam (nip);
CREATE INDEX IF NOT EXISTS idx_token ON cbt_exam (token);
CREATE INDEX IF NOT EXISTS idx_ujian_nis ON cbt_sesi (ujian_id, nis);
CREATE INDEX IF NOT EXISTS idx_ujian ON cbt_soal (ujian_id);
CREATE INDEX IF NOT EXISTS idx_kelas_aktif ON cbt_ujian (kelas, aktif);
CREATE INDEX IF NOT EXISTS idx_token ON cbt_ujian (token);
CREATE INDEX IF NOT EXISTS idx_nip ON dokumen (nip);
CREATE INDEX IF NOT EXISTS idx_kelas ON inventaris (kelas);
CREATE INDEX IF NOT EXISTS idx_kelas ON jadwal_pelajaran (kelas);
CREATE INDEX IF NOT EXISTS idx_nip ON jadwal_pelajaran (nip);
CREATE INDEX IF NOT EXISTS idx_kelas ON jadwal_piket (kelas);
CREATE INDEX IF NOT EXISTS idx_kelas ON jurnal_bimbingan (kelas);
CREATE INDEX IF NOT EXISTS idx_nip ON jurnal_mengajar (nip);
CREATE INDEX IF NOT EXISTS idx_tgl ON kalender_akademik (tanggal);
CREATE INDEX IF NOT EXISTS idx_kelas ON kaskelas (kelas);
CREATE INDEX IF NOT EXISTS idx_kelas_tgl ON kehadiran (kelas, tanggal);
CREATE INDEX IF NOT EXISTS idx_nip ON kkm (nip);
CREATE INDEX IF NOT EXISTS idx_kelas ON kunjungan_rumah (kelas);
CREATE INDEX IF NOT EXISTS idx_nip ON materi (nip);
CREATE INDEX IF NOT EXISTS idx_nip ON modul_ajar (nip);
CREATE INDEX IF NOT EXISTS idx_nip_kelas ON nilai (nip, kelas);
CREATE INDEX IF NOT EXISTS idx_tugas ON pengumpulan (tugas_id);
CREATE INDEX IF NOT EXISTS idx_kelas ON pengumuman (kelas);
CREATE INDEX IF NOT EXISTS idx_nis ON portofolio (nis);
CREATE INDEX IF NOT EXISTS idx_nip ON presensi_guru (nip);
CREATE INDEX IF NOT EXISTS idx_nip_kelas ON presensi_mapel (nip, kelas);
CREATE INDEX IF NOT EXISTS idx_kelas ON siswa (kelas);
CREATE INDEX IF NOT EXISTS idx_nis ON siswa (nis);
CREATE INDEX IF NOT EXISTS idx_kelas ON struktur_kelas (kelas);
CREATE INDEX IF NOT EXISTS idx_kelas ON tatatertib (kelas);
CREATE INDEX IF NOT EXISTS idx_nip ON tugas (nip);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_exam_nis ON cbt_hasil (exam_id, nis);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_sesi_soal ON cbt_jawaban (sesi_id, soal_id);
CREATE UNIQUE INDEX IF NOT EXISTS setting_key ON settings (setting_key);
CREATE UNIQUE INDEX IF NOT EXISTS username ON users (username);
