#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const schema = fs.readFileSync(path.join(root, 'schema.sql'), 'utf8');
const data = fs.readFileSync(path.join(root, 'data.sql'), 'utf8');

function convertSchema(sql) {
  // 1. Remove backticks
  let s = sql.replace(/`/g, '');
  // 2. AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY
  s = s.replace(/INTEGER\s+NOT\s+NULL\s+PRIMARY\s+KEY\s+AUTOINCREMENT/gi, 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  s = s.replace(/INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT/gi, 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  // 3. DEFAULT NULL -> just omit (or keep)
  s = s.replace(/DEFAULT\s+NULL/gi, '');
  // 4. Remove ENGINE, CHARSET, COLLATE, ROW_FORMAT, etc.
  s = s.replace(/ENGINE\s*=\s*\S+/gi, '');
  s = s.replace(/CHARSET\s*=\s*\S+/gi, '');
  s = s.replace(/COLLATE\s*=\s*\S+/gi, '');
  s = s.replace(/ROW_FORMAT\s*=\s*\S+/gi, '');
  s = s.replace(/DEFAULT\s+CHARSET\s*=\s*\S+/gi, '');
  // 5. Remove UNIQUE KEY / KEY / INDEX lines (they are separate CREATE INDEX elsewhere? Actually in schema they are inline)
  // For safety, remove KEY lines (MySQL style)
  s = s.replace(/^\s*KEY\s+`?\w+`?\s*\([^)]*\),?\s*$/gmi, '');
  // 6. Remove trailing commas before closing parenthesis
  s = s.replace(/,\s*\)/g, ')');
  // 7. Remove extra whitespace
  s = s.replace(/\n\s*\n/g, '\n');
  return s;
}

function convertData(sql) {
  // 1. Replace backticks in table names
  let s = sql.replace(/`/g, '');
  // 2. Escape single quotes properly: \' -> '' (Postgres)
  s = s.replace(/\\'/g, "''");
  // 3. Remove ENGINE, CHARSET, etc if any
  s = s.replace(/ENGINE\s*=\s*\S+/gi, '');
  s = s.replace(/CHARSET\s*=\s*\S+/gi, '');
  s = s.replace(/COLLATE\s*=\s*\S+/gi, '');
  s = s.replace(/ROW_FORMAT\s*=\s*\S+/gi, '');
  return s;
}

fs.writeFileSync(path.join(root, 'schema.pg.sql'), convertSchema(schema));
fs.writeFileSync(path.join(root, 'data.pg.sql'), convertData(data));
console.log('Converted schema.pg.sql and data.pg.sql');